basePath: /api/v1
definitions:
  factories.APIErrorMessageFactory:
    properties:
      error:
        type: string
    type: object
  factories.APISuccessMessageFactory:
    properties:
      success:
        type: string
    type: object
  factories.SingleUserFactory:
    properties:
      created_at:
        type: string
      id:
        type: integer
      mailaddress:
        type: string
      password:
        type: string
      status:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  factories.TopMessageFactory:
    properties:
      announcements:
        items:
          type: '&{entities TopAnnouncement}'
        type: array
      detail:
        type: string
      title:
        type: string
      version:
        type: string
    type: object
  factories.UserItemsFactory:
    properties:
      users:
        items:
          $ref: '#/definitions/factories.SingleUserFactory'
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: just1factory@gmail.com
    name: fumiyasac
    url: https://qiita.com/fumiyasac@github
  description: This is a sample API server. (This is a practice of fumiyasac.)
  license: {}
  title: Sample API
  version: "1.0"
paths:
  /top:
    get:
      consumes:
      - application/json
      description: TOP用の挨拶メッセージとこのAPIに関する概要や現行バージョン・更新履歴を表示する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/factories.TopMessageFactory'
            type: object
      summary: このAPIに関するメッセージを表示する
  /users:
    get:
      consumes:
      - application/json
      description: userテーブルに登録されているデータを全件取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/factories.UserItemsFactory'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/factories.APIErrorMessageFactory'
            type: object
      summary: ユーザー一覧を表示する
    post:
      consumes:
      - application/json
      description: userテーブルへ新規データを1件登録する
      parameters:
      - description: '(リクエストで有効なJSONの値) username: ユーザー名 ・ password: パスワード ・ mailaddress:
          メールアドレス'
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/factories.APISuccessMessageFactory'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/factories.APIErrorMessageFactory'
            type: object
      summary: ユーザーデータを1件新規登録する
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: userテーブルに登録されているデータのうちパラメーター(id)に該当するものを1件削除する
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/factories.APISuccessMessageFactory'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/factories.APIErrorMessageFactory'
            type: object
      summary: ユーザーデータを1件削除する
    get:
      consumes:
      - application/json
      description: userテーブルに登録されているデータのうちパラメーター(id)に該当するものを1件取得する
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/factories.SingleUserFactory'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/factories.APIErrorMessageFactory'
            type: object
      summary: ユーザーデータを1件表示する
    put:
      consumes:
      - application/json
      description: userテーブルに登録されているデータのうちパラメーター(id)に該当するものを1件更新する
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: integer
      - description: '(リクエストで有効なJSONの値) username: ユーザー名 ・ password: パスワード ・ mailaddress:
          メールアドレス'
        in: body
        name: request
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/factories.APISuccessMessageFactory'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/factories.APIErrorMessageFactory'
            type: object
      summary: ユーザーデータを1件更新する
swagger: "2.0"
